# Site settings
title: ManyPrimates
subtitle: 
email: manyprimates@gmail.com
description: ManyPrimates | Establishing a Culture of Collaboration in Primate Cognition Research
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://manyprimates.github.io" # the base hostname & protocol for your site
author: ManyPrimates

# Social settings
github_url: https://github.com/ManyPrimates
slack_url: https://manyprimates.slack.com
twitter_url: https://twitter.com/ManyPrimates
osf_url: https://osf.io/tr6q3/

# Build settings
markdown: kramdown
